name: serve

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          cd serve
          npm ci
          npm test
        env:
          CI: true
      - name: deploy
        if: contains(github.ref, 'master')
        run: |
          cd serve
          mkdir .now
          echo '{"projectId":"${{ secrets.NOW_PROJECT }}", "orgId": "${{ secrets.NOW_ORG }}"}' >> ./.now/project.json
          npm install now
          npm run build
          npx now --public --token ${{ secrets.NOW_TOKEN }}
          npx now --prod --token ${{ secrets.NOW_TOKEN }}
